import Hero from "./components/Hero";
import Logo from "./components/Logo";
import "./globals.css";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // redirect('/dashboard');

  return (
    <html lang="en">
      <body>
        <Logo />

        <main className="mx-auto max-w-[100rem] h-full">
          <Hero />
          {children}
        </main>
      </body>
    </html>
  );
}
